# Generated by Django 4.2.13 on 2024-06-10 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('center_x', models.IntegerField()),
                ('center_y', models.IntegerField()),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('records', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location_x', models.IntegerField()),
                ('location_y', models.IntegerField()),
                ('capital', models.BooleanField(default=False)),
                ('commoners', models.IntegerField()),
                ('gentry', models.IntegerField()),
                ('district', models.IntegerField()),
                ('structures', models.IntegerField()),
                ('total_taxes', models.IntegerField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_data.region')),
            ],
        ),
        migrations.CreateModel(
            name='TownMarketData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('last_price', models.IntegerField()),
                ('average_price', models.IntegerField()),
                ('moving_average', models.IntegerField()),
                ('highest_bid', models.IntegerField()),
                ('lowest_ask', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('volume_prev_12', models.IntegerField()),
                ('bid_volume_10', models.IntegerField()),
                ('ask_volume_10', models.IntegerField()),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_data.town')),
            ],
        ),
    ]
