# Generated by Django 4.2.13 on 2024-06-11 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('production_capacity', models.IntegerField()),
                ('location_x', models.IntegerField(blank=True, null=True)),
                ('location_y', models.IntegerField(blank=True, null=True)),
                ('delivery_cost', models.FloatField(blank=True, null=True)),
                ('delivery_land_distance', models.FloatField(blank=True, null=True)),
                ('capacity', models.FloatField(blank=True, null=True)),
                ('limited', models.BooleanField(default=False)),
                ('recipe', models.CharField(blank=True, max_length=255, null=True)),
                ('manager', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuildingUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('access', models.TextField()),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ConstructionRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_counter', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=255)),
                ('requirement', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
                ('obligations', models.CharField(max_length=255)),
                ('reward', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('delivery_1', 'Delivery Duty 1'), ('delivery_2', 'Delivery Duty 2'), ('knight_1', 'Knight Duty 1'), ('knight_2', 'Knight Duty 2'), ('knight_3', 'Knight Duty 3'), ('knight_4', 'Knight Duty 4')], max_length=255)),
                ('duty_cost', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField()),
                ('reserved', models.FloatField()),
                ('capacity', models.FloatField(blank=True, null=True)),
                ('unit_cost', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('required_level', models.IntegerField(blank=True, null=True)),
                ('commoner_purchase', models.BooleanField(default=False)),
                ('town_purchase', models.BooleanField(default=False)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('size', models.FloatField(blank=True, null=True)),
                ('calories', models.FloatField(blank=True, null=True)),
                ('price_low', models.FloatField(blank=True, null=True)),
                ('price_typical', models.FloatField(blank=True, null=True)),
                ('price_high', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
                ('tier', models.IntegerField(blank=True, null=True)),
                ('classes', models.ManyToManyField(blank=True, to='game_data.classtype')),
                ('required_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='required_by_items', to='game_data.classtype')),
            ],
        ),
        migrations.CreateModel(
            name='OperatingCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_data.item')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('leaderboard_position', models.IntegerField(blank=True, null=True)),
                ('rushes', models.IntegerField(default=3)),
                ('prestige', models.FloatField(blank=True, null=True)),
                ('portrait', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('caps_transports', models.IntegerField(default=0)),
                ('caps_buildings', models.IntegerField(default=0)),
                ('caps_prestige_buildings', models.IntegerField(default=0)),
                ('caps_farmsteads', models.IntegerField(default=0)),
                ('caps_tenants', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PrestigeBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('label', models.CharField(choices=[('common', 'Common'), ('established', 'Established'), ('reputable', 'Reputable'), ('distinguished', 'Distinguished'), ('exalted', 'Exalted'), ('legend', 'Legend')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('tenants_bonus', models.IntegerField(default=0)),
                ('total_tenants', models.IntegerField(default=0)),
                ('luxury_consumption_bonus', models.IntegerField(default=0)),
                ('total_luxury_consumption', models.IntegerField(default=0)),
                ('apprentice_bonus', models.IntegerField(default=0)),
                ('total_apprentices', models.IntegerField(default=0)),
                ('building_capacity_bonus', models.IntegerField(default=0)),
                ('total_building_capacity', models.IntegerField(default=0)),
                ('transport_capacity_bonus', models.IntegerField(default=0)),
                ('total_transport_capacity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('labor_required', models.FloatField()),
                ('requires_master_level_worker', models.BooleanField(default=False)),
                ('tier', models.IntegerField(blank=True, null=True)),
                ('building', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('class_field', models.CharField(blank=True, max_length=255, null=True)),
                ('points', models.FloatField(blank=True, null=True)),
                ('class_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_data.classtype')),
                ('required_building_upgrade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_data.buildingupgrade')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('center_x', models.IntegerField()),
                ('center_y', models.IntegerField()),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number_of_moves', models.IntegerField()),
                ('distance', models.FloatField()),
                ('is_land_route', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SustenanceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TileAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location_x', models.IntegerField()),
                ('location_y', models.IntegerField()),
                ('capital', models.BooleanField(default=False)),
                ('commoners', models.IntegerField()),
                ('gentry', models.IntegerField()),
                ('district', models.IntegerField()),
                ('structures', models.IntegerField()),
                ('total_taxes', models.IntegerField()),
                ('climate', models.CharField(choices=[('cold', 'Cold'), ('warm', 'Warm')], default='warm', max_length=10)),
                ('growth_rate', models.FloatField(default=0.0)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_data.region')),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('size', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('location_x', models.IntegerField(blank=True, null=True)),
                ('location_y', models.IntegerField(blank=True, null=True)),
                ('capacity', models.FloatField()),
                ('provider_id', models.CharField(blank=True, max_length=255, null=True)),
                ('hometown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hometown', to='game_data.town')),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game_data.inventory')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_data.player')),
                ('route', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game_data.route')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_town', to='game_data.town')),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.IntegerField()),
                ('month', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('work_capacity', models.IntegerField(choices=[(15, '15'), (25, '25')])),
                ('is_head_of_household', models.BooleanField(default=False)),
                ('skills', models.JSONField(blank=True, null=True)),
                ('current_building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_data.building')),
                ('current_duty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_data.householdduty')),
                ('current_transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_data.transport')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_master', models.BooleanField(default=False)),
                ('class_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_data.classtype')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_data.classlevel')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_data.worker')),
            ],
        ),
        migrations.CreateModel(
            name='TransportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('tier', models.IntegerField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('journey_duration', models.FloatField(blank=True, null=True)),
                ('effective_days', models.IntegerField(blank=True, null=True)),
                ('catches', models.CharField(blank=True, max_length=255, null=True)),
                ('fishing_range', models.IntegerField(blank=True, null=True)),
                ('operating_costs', models.ManyToManyField(through='game_data.OperatingCost', to='game_data.item')),
            ],
        ),
        migrations.AddField(
            model_name='transport',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_data.transporttype'),
        ),
        migrations.CreateModel(
            name='TownPurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_data.item')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_data.town')),
            ],
        ),
        migrations.CreateModel(
            name='TileTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_amount', models.FloatField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_data.tileattribute')),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ask_price', models.FloatField(blank=True, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_data.building')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_data.player')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_data.region')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_data.town')),
            ],
        ),
        migrations.CreateModel(
            name='Sync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('records', models.IntegerField()),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_data.turn')),
            ],
        ),
        migrations.CreateModel(
            name='SustenanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('units_required', models.FloatField()),
                ('prestige_effect', models.FloatField()),
                ('prestige_penalty', models.FloatField(default=0)),
                ('unit_cost', models.FloatField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_data.sustenancecategory')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_data.item')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='destination_town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_routes', to='game_data.town'),
        ),
        migrations.AddField(
            model_name='route',
            name='game_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='game_data.player'),
        ),
        migrations.AddField(
            model_name='route',
            name='starting_town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_routes', to='game_data.town'),
        ),
        migrations.CreateModel(
            name='RecipeOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='game_data.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='game_data.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='PreviousFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption', models.FloatField(blank=True, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_flows', to='game_data.building')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_data.item')),
            ],
        ),
        migrations.CreateModel(
            name='PrestigeImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.CharField(max_length=255)),
                ('impact', models.FloatField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestige_impacts', to='game_data.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSustenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_data.sustenanceitem')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_data.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='head_of_household',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_of_household_for', to='game_data.worker'),
        ),
        migrations.AddField(
            model_name='player',
            name='household_inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_household', to='game_data.inventory'),
        ),
        migrations.AddField(
            model_name='player',
            name='town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_data.town'),
        ),
        migrations.AddField(
            model_name='player',
            name='workers',
            field=models.ManyToManyField(blank=True, to='game_data.worker'),
        ),
        migrations.AddField(
            model_name='operatingcost',
            name='transport_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_data.transporttype'),
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('last_price', models.FloatField()),
                ('average_price', models.FloatField()),
                ('moving_average', models.FloatField()),
                ('highest_bid', models.FloatField()),
                ('lowest_ask', models.FloatField()),
                ('volume', models.IntegerField()),
                ('volume_prev_12', models.IntegerField()),
                ('bid_volume_10', models.IntegerField()),
                ('ask_volume_10', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_data.item')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_holding', models.IntegerField(blank=True, null=True)),
                ('buy_volume', models.IntegerField(blank=True, null=True)),
                ('buy_price', models.FloatField(blank=True, null=True)),
                ('sell_volume', models.IntegerField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_data.item')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_data.player')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_data.item'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_data.player'),
        ),
        migrations.CreateModel(
            name='HouseholdCaps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transports', models.IntegerField()),
                ('buildings', models.IntegerField()),
                ('prestige_buildings', models.IntegerField()),
                ('farmsteads', models.IntegerField()),
                ('tenants', models.IntegerField()),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caps', to='game_data.player')),
            ],
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption', models.FloatField(blank=True, null=True)),
                ('shortfall', models.FloatField(blank=True, null=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='game_data.building')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='game_data.item')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='game_data.player')),
                ('transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='game_data.transport')),
            ],
        ),
        migrations.CreateModel(
            name='ContractItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_data.contract')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_data.item')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='assigned_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_data.player'),
        ),
        migrations.AddField(
            model_name='contract',
            name='deadline_turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_data.turn'),
        ),
        migrations.AddField(
            model_name='contract',
            name='items',
            field=models.ManyToManyField(through='game_data.ContractItem', to='game_data.item'),
        ),
        migrations.AddField(
            model_name='contract',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_data.town'),
        ),
        migrations.CreateModel(
            name='ConstructionRequirementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('construction_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_data.constructionrequirement')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_data.item')),
            ],
        ),
        migrations.AddField(
            model_name='constructionrequirement',
            name='items',
            field=models.ManyToManyField(through='game_data.ConstructionRequirementItem', to='game_data.item'),
        ),
        migrations.CreateModel(
            name='CommonerPurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_data.item')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_data.town')),
            ],
        ),
        migrations.AddField(
            model_name='buildingupgrade',
            name='construction_requirement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game_data.constructionrequirement'),
        ),
        migrations.AddField(
            model_name='buildingupgrade',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='required_by', to='game_data.buildingupgrade'),
        ),
        migrations.CreateModel(
            name='BuildingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('production_capacity', models.IntegerField()),
                ('build_location', models.CharField(max_length=255)),
                ('expansion_discount', models.FloatField(blank=True, null=True)),
                ('supports_boost', models.BooleanField(default=False)),
                ('classes', models.ManyToManyField(blank=True, to='game_data.classtype')),
                ('construction_requirement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game_data.constructionrequirement')),
                ('required_tile_attributes', models.ManyToManyField(blank=True, to='game_data.tileattribute')),
                ('upgrades', models.ManyToManyField(blank=True, related_name='upgraded_by', to='game_data.buildingupgrade')),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='building_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_data.buildingtype'),
        ),
        migrations.AddField(
            model_name='building',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game_data.inventory'),
        ),
        migrations.AddField(
            model_name='building',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_data.player'),
        ),
        migrations.AddField(
            model_name='building',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_data.town'),
        ),
        migrations.AddField(
            model_name='building',
            name='upgrades',
            field=models.ManyToManyField(blank=True, to='game_data.buildingupgrade'),
        ),
        migrations.CreateModel(
            name='RouteStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.IntegerField()),
                ('coordinate_x', models.IntegerField()),
                ('coordinate_y', models.IntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='game_data.route')),
            ],
            options={
                'ordering': ['sequence_number'],
                'unique_together': {('route', 'sequence_number')},
            },
        ),
    ]
